title: Vilmos Horváth
baseurl: "/portfolio"
url: "https://vilok-vii.github.io"

languages: ["en", "hu"]

collections:
  projects:
    output: true

defaults:
  - scope:
      path: "_projects/en"
      type: projects
    values:
      lang: en
      layout: project
      section: projects
      permalink: /en/projects/:name/
  - scope:
      path: "_projects/hu"
      type: projects
    values:
      lang: hu
      layout: project
      section: projects
      permalink: /hu/projects/:name/

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
